/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Poppins', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        primary: ['var(--petgas-font-primary)'],
        mono: ['var(--petgas-font-mono)'],
      },
      fontSize: {
        'xs': 'var(--petgas-text-xs)',
        'sm': 'var(--petgas-text-sm)',
        'base': 'var(--petgas-text-base)',
        'lg': 'var(--petgas-text-lg)',
        'xl': 'var(--petgas-text-xl)',
        '2xl': 'var(--petgas-text-2xl)',
        '3xl': 'var(--petgas-text-3xl)',
        '4xl': 'var(--petgas-text-4xl)',
        '5xl': 'var(--petgas-text-5xl)',
        '6xl': 'var(--petgas-text-6xl)',
        '7xl': 'var(--petgas-text-7xl)',
        '8xl': 'var(--petgas-text-8xl)',
        '9xl': 'var(--petgas-text-9xl)',
      },
      fontWeight: {
        'thin': 'var(--petgas-font-thin)',
        'extralight': 'var(--petgas-font-extralight)',
        'light': 'var(--petgas-font-light)',
        'normal': 'var(--petgas-font-regular)',
        'medium': 'var(--petgas-font-medium)',
        'semibold': 'var(--petgas-font-semibold)',
        'bold': 'var(--petgas-font-bold)',
        'extrabold': 'var(--petgas-font-extrabold)',
        'black': 'var(--petgas-font-black)',
      },
      lineHeight: {
        'none': 'var(--petgas-leading-none)',
        'tight': 'var(--petgas-leading-tight)',
        'snug': 'var(--petgas-leading-snug)',
        'normal': 'var(--petgas-leading-normal)',
        'relaxed': 'var(--petgas-leading-relaxed)',
        'loose': 'var(--petgas-leading-loose)',
      },
      colors: {
        // Legacy colors for backward compatibility
        border: 'rgba(var(--color-border) / 0.5)',
        input: 'rgb(var(--color-input))',
        ring: 'rgb(var(--color-ring))',
        background: 'rgb(var(--color-background))',
        foreground: 'rgb(var(--color-foreground))',
        primary: {
          DEFAULT: 'rgb(var(--color-primary))',
          hover: 'rgb(var(--color-primary-hover))',
          foreground: 'hsl(var(--color-foreground))',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary))',
          foreground: 'hsl(var(--color-foreground))',
        },
        accent: {
          DEFAULT: 'rgb(var(--color-accent))',
          foreground: 'hsl(var(--color-foreground))',
        },
        muted: {
          DEFAULT: 'rgb(var(--color-muted))',
          foreground: 'rgb(var(--color-muted-foreground))',
        },
        // New PetGas design system colors
        petgas: {
          gold: 'var(--petgas-gold)',
          'gold-light': 'var(--petgas-gold-light)',
          'gold-dark': 'var(--petgas-gold-dark)',
          goldenrod: 'var(--petgas-goldenrod)',
          amber: 'var(--petgas-amber)',
          orange: 'var(--petgas-orange)',
          black: 'var(--petgas-black)',
          dark: 'var(--petgas-dark)',
          gray: 'var(--petgas-gray)',
          'gray-light': 'var(--petgas-gray-light)',
          'gray-lighter': 'var(--petgas-gray-lighter)',
          'text-light': 'var(--petgas-text-light)',
          'text-white': 'var(--petgas-text-white)',
          'text-muted': 'var(--petgas-text-muted)',
          'text-gray': 'var(--petgas-text-gray)',
        },
      },
      backgroundImage: {
        'petgas-gradient-primary': 'var(--petgas-gradient-primary)',
        'petgas-gradient-secondary': 'var(--petgas-gradient-secondary)',
        'petgas-gradient-button': 'var(--petgas-gradient-button)',
        'petgas-gradient-text': 'var(--petgas-gradient-text)',
        'petgas-gradient-background': 'var(--petgas-gradient-background)',
        'petgas-gradient-card': 'var(--petgas-gradient-card)',
        'petgas-gradient-overlay': 'var(--petgas-gradient-overlay)',
        'petgas-gradient-radial': 'var(--petgas-gradient-radial)',
        'petgas-gradient-glow': 'var(--petgas-gradient-glow)',
      },
      spacing: {
        '0': 'var(--petgas-space-0)',
        '1': 'var(--petgas-space-1)',
        '2': 'var(--petgas-space-2)',
        '3': 'var(--petgas-space-3)',
        '4': 'var(--petgas-space-4)',
        '5': 'var(--petgas-space-5)',
        '6': 'var(--petgas-space-6)',
        '8': 'var(--petgas-space-8)',
        '10': 'var(--petgas-space-10)',
        '12': 'var(--petgas-space-12)',
        '16': 'var(--petgas-space-16)',
        '20': 'var(--petgas-space-20)',
        '24': 'var(--petgas-space-24)',
        '32': 'var(--petgas-space-32)',
      },
      boxShadow: {
        'petgas-sm': 'var(--petgas-shadow-sm)',
        'petgas': 'var(--petgas-shadow-base)',
        'petgas-md': 'var(--petgas-shadow-md)',
        'petgas-lg': 'var(--petgas-shadow-lg)',
        'petgas-xl': 'var(--petgas-shadow-xl)',
        'petgas-2xl': 'var(--petgas-shadow-2xl)',
        'petgas-glow': 'var(--petgas-shadow-glow)',
        'petgas-glow-lg': 'var(--petgas-shadow-glow-lg)',
      },
      transitionDuration: {
        'fast': 'var(--petgas-transition-fast)',
        'base': 'var(--petgas-transition-base)',
        'slow': 'var(--petgas-transition-slow)',
        'slower': 'var(--petgas-transition-slower)',
      },
      zIndex: {
        'hide': 'var(--petgas-z-hide)',
        'auto': 'var(--petgas-z-auto)',
        'base': 'var(--petgas-z-base)',
        'docked': 'var(--petgas-z-docked)',
        'dropdown': 'var(--petgas-z-dropdown)',
        'sticky': 'var(--petgas-z-sticky)',
        'banner': 'var(--petgas-z-banner)',
        'overlay': 'var(--petgas-z-overlay)',
        'modal': 'var(--petgas-z-modal)',
        'popover': 'var(--petgas-z-popover)',
        'skipLink': 'var(--petgas-z-skipLink)',
        'toast': 'var(--petgas-z-toast)',
        'tooltip': 'var(--petgas-z-tooltip)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'petgas-shine': {
          '0%': { backgroundPosition: '0% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        'petgas-pulse-glow': {
          '0%, 100%': {
            opacity: '1',
            transform: 'scale(1)',
          },
          '50%': {
            opacity: '0.8',
            transform: 'scale(1.02)',
          },
        },
        'petgas-float': {
          '0%, 100%': {
            transform: 'translateY(0px)',
          },
          '50%': {
            transform: 'translateY(-10px)',
          },
        },
        'petgas-gradient-shift': {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        'petgas-glow-pulse': {
          '0%, 100%': {
            boxShadow: 'var(--petgas-shadow-glow)',
          },
          '50%': {
            boxShadow: 'var(--petgas-shadow-glow-lg)',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'petgas-shine': 'petgas-shine 3s linear infinite',
        'petgas-pulse-glow': 'petgas-pulse-glow 2s ease-in-out infinite',
        'petgas-float': 'petgas-float 3s ease-in-out infinite',
        'petgas-gradient-shift': 'petgas-gradient-shift 3s ease infinite',
        'petgas-glow-pulse': 'petgas-glow-pulse 2s ease-in-out infinite',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
  ],
}
